const words = [
    "chat", "chien", "maison", "ordinateur", "programme", "musique", "livre", "voiture", "banane", "avion",
    "jardin", "école", "football", "pizza", "hôpital", "arbre", "soleil", "plage", "montagne", "café",
    "étoile", "voyage", "fleur", "rue", "table", "chaise", "moto", "fruit", "lac", "route",
    "feu", "forêt", "guitare", "piano", "violon", "basketball", "piscine", "hiver", "été", "printemps",
    "automne", "fenêtre", "porte", "bateau", "train", "téléphone", "ordinateur portable", "gâteau", "chocolat", "glace",
    "souris", "clavier", "stylo", "crayon", "couleur", "danse", "parc", "caméra", "photo", "ciel",
    "terre", "mer", "cuisine", "restaurant", "marché", "ville", "musée", "film", "théâtre", "spectacle",
    "spectateur", "artiste", "peinture", "sculpture", "poème", "rêve", "nuit", "jour", "heure", "minute",
    "seconde", "balade", "randonnée", "escalade", "voyage", "exploration", "aventure", "découverte", "nature", "animaux",
    "oiseau", "lion", "tigre", "éléphant", "girafe", "singe", "chaton", "chiot", "lapin", "écureuil",
    "abeille", "papillon", "fraise", "citron", "pomme", "poire", "raisin", "ananas", "orange", "pastèque",
    "tomate", "courgette", "aubergine", "poivron", "brocoli", "carotte", "oignon", "ail", "sel", "poivre",
    "sucre", "farine", "riz", "pâtes", "sel", "poivre", "sauce", "huile", "vinaigre", "jus",
    "eau", "bière", "vin", "café", "thé", "lait", "yaourt", "fromage", "beurre", "pain",
    "viande", "poisson", "poulet", "porc", "boeuf", "agneau", "veau", "oeuf", "crème", "chocolat",
    "bonbon", "sucre", "miel", "noix", "amande", "noisette", "cacahuète", "noix de cajou", "noix de coco", "sel",
    "poivre", "épice", "herbe", "fleur", "parfum", "savon", "shampoing", "dentifrice", "brosse à dents", "serviette",
    "savon", "shampoing", "dentifrice", "brosse à dents", "serviette", "télévision", "radio", "journal", "magazine", "journaliste", "émission", "publicité", "documentaire", "fiction", "série", "comédie", "drame", "thriller", "action", "romance", "fantaisie", "science-fiction", "histoire", "géographie", "mathématiques", "physique", "chimie", "biologie", "informatique", "économie", "sourire", "réussite", "argent", "énergie", "réflexion", "imagination", "travail", "équipe", "espace", "planète", "univers", "terre", "ciel", "étoile", "constellation", "galaxie", "astronaute", "étoile filante", "planète naine", "système solaire",
    "orbite", "gravité", "temps", "passé", "présent", "futur", "souvenir", "histoire", "événement", "révolution",
    "découverte", "avancée", "innovation", "créativité", "inspiration", "passion", "joie", "peine", "résilience", "effort",
    "persévérance", "courage", "beauté", "harmonie", "équilibre", "justice", "liberté", "respect", "tolérance", "diversité", "sourire", "réussite", "argent", "énergie", "réflexion", "imagination", "travail", "équipe", "espace", "planète",
    "univers", "terre", "ciel", "étoile", "constellation", "galaxie", "astronaute", "étoile filante", "planète naine", "système solaire", "orbite", "gravité", "temps", "passé", "présent", "futur", "souvenir", "histoire", "événement", "révolution", "découverte", "avancée", "innovation", "créativité", "inspiration", "passion", "joie", "peine", "résilience", "effort", "persévérance", "courage", "beauté", "harmonie", "équilibre", "justice", "liberté", "respect", "tolérance", "diversité",
    "émotion", "sentiment", "amitié", "amour", "haine", "colère", "tristesse", "joie", "bonheur", "sérénité",
    "mélancolie", "espoir", "confiance", "peur", "courage", "audace", "surprise", "déception", "compassion", "fierté",
    "humilité", "générosité", "gratitude", "patience", "tolérance", "persévérance", "émerveillement", "doute", "curiosité", "ambition", "succès", "échec", "rencontre", "communication", "dialogue", "écoute", "silence", "parole", "expression", "langage", "culture", "tradition", "coutume", "rituel", "spiritualité", "religion", "croyance", "science", "connaissance", "sagesse", "vérité", "mensonge", "illusion", "réalité", "fantaisie", "rêve", "imagination", "création", "art", "musique",
    "peinture", "sculpture", "danse", "théâtre", "cinéma", "littérature", "poésie", "architecture", "photographie", "design",
    "nature", "environnement", "écologie", "biodiversité", "forêt", "océan", "montagne", "désert", "jardin", "flore",
    "faune", "animaux", "plantes", "végétation", "air", "eau", "feu", "terre", "paysage", "saison",
    "printemps", "été", "automne", "hiver", "jour", "nuit", "aube", "crépuscule", "éclipse", "horizon",
    "aventure", "exploration", "voyage", "découverte", "expérience", "frontière", "limites", "challenge", "résolution", "objectif", "santé", "bien-être", "équilibre", "alimentation", "nutrition", "exercice", "sport", "forme physique", "mental", "esprit", "méditation", "zen", "yoga", "soins", "relaxation", "sommeil", "énergie", "vitalité", "régénération", "stress", "confort", "détente", "plaisir", "passion", "hobby", "loisirs", "divertissement", "jeux", "amusant", "fête",
    "anniversaire", "mariage", "célébration", "danse", "musique", "spectacle", "concert", "artiste", "performance", "créativité", "technologie", "innovation", "numérique", "intelligence artificielle", "robotique", "internet", "réseau", "données", "programmation", "algorithme", "communication", "réseaux sociaux", "smartphone", "ordinateur", "gadget", "gaming", "virtuel", "réalité augmentée", "cybersécurité", "cryptomonnaie", "économie", "commerce", "entreprise", "startup", "investissement", "finance", "marché", "consommation", "entrepreneuriat", "croissance", "travail", "carrière", "emploi", "bureau", "productivité", "organisation", "leadership", "collaboration", "créativité", "équipe", "éducation", "apprentissage", "école", "université", "étudiant", "enseignement", "professeur", "savoir", "discipline", "curriculum",
    "science", "mathématiques", "physique", "chimie", "biologie", "histoire", "géographie", "langue", "culture", "art",
    "philosophie", "psychologie", "sociologie", "politique", "éthique", "environnement", "droits", "justice", "égalité", "citoyenneté"
];

